version: "3.7"

services:
  db:
    image: postgres
    container_name: db
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=123456
    restart: always
    volumes: 
      - "dbdata:/var/lib/postgresql/data"
    networks:
      - dev
  server:
    build:
      context: ./serve
      dockerfile: Dockerfile
    # image: docker-pcr_server
    restart: always
    volumes: 
      - "log:/root/server/src/log"
      - "sqlite:/root/server/src/assets"
    ports:
      - 5000:5000
    depends_on: # 需要依赖的服务，在依赖起来之后才会再起
      - db
    networks:
      - dev
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:80
    container_name: web
    depends_on:
      - server
    networks:
      - dev
  webadminjp:
    build:
      context: ./webAdminjp
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8888:80
    container_name: webadminjp
    depends_on:
      - server
    networks:
      - dev
networks: # 同网络
  dev:
volumes:
  dbdata:
  log:
  sqlite:
